// <auto-generated />
namespace gliist_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Event_RsvpAndTicketingUrlAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Event_RsvpAndTicketingUrlAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201509241332419_Event_RsvpAndTicketingUrlAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
