// <auto-generated />
namespace gliist_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GuestList_PromoterId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GuestList_PromoterId));
        
        string IMigrationMetadata.Id
        {
            get { return "201512160746585_GuestList_PromoterId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
