// <auto-generated />
namespace gliist_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Guest_LastName_RemoveRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Guest_LastName_RemoveRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201512080823090_Guest_LastName_RemoveRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
