// <auto-generated />
namespace gliist_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Event_IsRsvpCapacityLimited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Event_IsRsvpCapacityLimited));
        
        string IMigrationMetadata.Id
        {
            get { return "201510060709336_Event_IsRsvpCapacityLimited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
