// <auto-generated />
namespace gliist_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class TicketTypes_Table_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketTypes_Table_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201508271236165_TicketTypes_Table_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
