// <auto-generated />
namespace gliist_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class gli_published : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gli_published));
        
        string IMigrationMetadata.Id
        {
            get { return "201507091721572_gli_published"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
