// <auto-generated />
namespace gliist_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Event_RSVP_Columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Event_RSVP_Columns));
        
        string IMigrationMetadata.Id
        {
            get { return "201508271359416_Event_RSVP_Columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
