// <auto-generated />
namespace gliist_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EventsGuests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventsGuests));
        
        string IMigrationMetadata.Id
        {
            get { return "201509021403169_EventsGuests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
