#!/bin/sh
HOST='waws-prod-bay-029.ftp.azurewebsites.windows.net'
USER="gjests__staging"
PASSWD="4uL7HB6TCL2tdY8buPZK4rXR1xG9v4zzeQwsgo8BqYC8hHAFD6w3Q30ZwsEf"
REMOTEPATH='site/wwwroot'

echo "============="
echo "Start build"
gulp clean
gulp build --force --env=staging
echo "Build done"
echo "Deploy to server"
cd ./dist
ncftpput -R -v -u "$USER" -p "$PASSWD" $HOST $REMOTEPATH .
echo "=============="
echo "Deploy finish"
exit 0