#!/bin/sh
HOST='ftps://staging-app.gjests.com'
USER="StagingDeploy"
REMOTEPATH='./'

echo "============="
echo "Start build"
gulp clean
gulp build --force --env=staging
echo "Build done"
echo "Deploy to server"
cd ./dist
lftp -c "open -u $USER $HOST; set ssl:verify-certificate no; mirror -R ./ $REMOTEPATH"
#ncftpput -R -v -u "$USER" $HOST $REMOTEPATH .
echo "=============="
echo "Deploy finish"
exit 0