#!/bin/sh
HOST='waws-prod-bay-029.ftp.azurewebsites.windows.net'
USER="gjests"
PASSWD="vZp4a7RtDMvqdo5nMzJzc4bFk9qybTeQWT6M1Hgs2mNY2gHXNfDkj5eG5KsG"
REMOTEPATH='site/wwwroot'

echo "============="
#echo "Start build"
#gulp build --force
#echo "Build done"
echo "Deploy to server"
cd ./dist
ncftpput -R -v -u "$USER" -p "$PASSWD" $HOST $REMOTEPATH .
echo "=============="
echo "Deploy finish"
exit 0